name: 'terraform-Azure'
on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
env: 
      ROOT_PATH: '.'
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
jobs:
  terraform_plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    #environment: production
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{secrets.AZURE_CLIENT_SECRET}}
    - name: terraform init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}
    - name: terraform Plan
      run: terraform plan 
      working-directory: ${{ env.ROOT_PATH }}